---
- name: Install computate-solr image stream on OpenShift
  k8s: 
    validate_certs: false
    state: present
    name: computate-scolaire
    host: "{{COMPUTATE_SCOLAIRE_HOST}}"
    api_key: "{{COMPUTATE_SCOLAIRE_TOKEN}}"
    namespace: "{{COMPUTATE_SCOLAIRE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_scolaire_image_stream.yml.j2') }}"
- name: Install computate-scolaire secret on OpenShift
  k8s: 
    validate_certs: false
    state: present
    name: computate-scolaire-secret
    host: "{{COMPUTATE_SCOLAIRE_HOST}}"
    api_key: "{{COMPUTATE_SCOLAIRE_TOKEN}}"
    namespace: "{{COMPUTATE_SCOLAIRE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_scolaire_secret.j2') }}"
- name: Install computate-scolaire keystore secrets on OpenShift
  k8s: 
    validate_certs: false
    state: present
    name: computate-scolaire-keystore
    host: "{{COMPUTATE_SCOLAIRE_HOST}}"
    api_key: "{{COMPUTATE_SCOLAIRE_TOKEN}}"
    namespace: "{{COMPUTATE_SCOLAIRE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_scolaire_keystore.j2') }}"
- name: Install computate-scolaire build config on OpenShift
  k8s: 
    validate_certs: false
    state: present
    name: computate-scolaire
    host: "{{COMPUTATE_SCOLAIRE_HOST}}"
    api_key: "{{COMPUTATE_SCOLAIRE_TOKEN}}"
    namespace: "{{COMPUTATE_SCOLAIRE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_scolaire_build_config.yml.j2') }}"
- name: Install computate-scolaire deployment config on OpenShift
  k8s: 
    validate_certs: false
    state: present
    name: computate-scolaire
    host: "{{COMPUTATE_SCOLAIRE_HOST}}"
    api_key: "{{COMPUTATE_SCOLAIRE_TOKEN}}"
    namespace: "{{COMPUTATE_SCOLAIRE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_scolaire_deployment_config.yml.j2') }}"
- name: Install computate-scolaire service on OpenShift
  k8s: 
    validate_certs: false
    state: present
    name: computate-scolaire
    host: "{{COMPUTATE_SCOLAIRE_HOST}}"
    api_key: "{{COMPUTATE_SCOLAIRE_TOKEN}}"
    namespace: "{{COMPUTATE_SCOLAIRE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_scolaire_service.yml.j2') }}"
- name: Install computate-scolaire route on OpenShift
  k8s: 
    validate_certs: false
    state: present
    name: computate-scolaire
    host: "{{COMPUTATE_SCOLAIRE_HOST}}"
    api_key: "{{COMPUTATE_SCOLAIRE_TOKEN}}"
    namespace: "{{COMPUTATE_SCOLAIRE_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_scolaire_route.yml.j2') }}"
- name: Create Solr collection
  shell: "oc login --insecure-skip-tls-verify {{COMPUTATE_SCOLAIRE_HOST}} --token={{REDHAT_OPENSHIFT_TOKEN}} && oc exec --insecure-skip-tls-verify $(oc get pod --insecure-skip-tls-verify -l app=computate-solr -o jsonpath='{.items[0].metadata.name}') -n {{ REDHAT_OPENSHIFT_NAMESPACE }} -- /opt/solr/bin/solr create_collection -c {{ COMPUTATE_SCOLAIRE_SOLR_COLLECTION }} -n computate || true"
  register: create_collection
- name: Print create_collection command
  debug:
    var: create_collection

