---
#- name: Install Ansible Tower persistent volume on OpenShift
#  k8s: 
#    validate_certs: false
#    state: present
#    name: "{{ REDHAT_ANSIBLE_TOWER_VOLUME_NAME }}"
#    host: "{{ REDHAT_ANSIBLE_TOWER_HOST }}"
#    api_key: "{{ REDHAT_ANSIBLE_TOWER_TOKEN }}"
#    namespace: "{{ REDHAT_ANSIBLE_TOWER_NAMESPACE }}"
#    definition: "{{ lookup('template', 'redhat_ansible_tower_persistent_volume.yml.j2') }}"
#- name: Install Ansible Tower persistent volume claim on OpenShift
#  k8s: 
#    validate_certs: false
#    state: present
#    name: "{{ REDHAT_ANSIBLE_TOWER_VOLUME_NAME }}"
#    host: "{{ REDHAT_ANSIBLE_TOWER_HOST }}"
#    api_key: "{{ REDHAT_ANSIBLE_TOWER_TOKEN }}"
#    namespace: "{{ REDHAT_ANSIBLE_TOWER_NAMESPACE }}"
#    definition: "{{ lookup('template', 'redhat_ansible_tower_persistent_volume_claim.yml.j2') }}"
- name: Download Ansible Tower installation setup files
  get_url:
    url: "https://releases.ansible.com/ansible-tower/setup_openshift/ansible-tower-openshift-setup-{{ REDHAT_ANSIBLE_TOWER_VERSION }}.tar.gz"
    dest: "/tmp/ansible-tower-openshift-setup-{{ REDHAT_ANSIBLE_TOWER_VERSION }}.tar.gz"
- name: Install Ansible Tower setup files into the /tmp/ansible-tower-setup directory. 
  unarchive: 
    src: "/tmp/ansible-tower-openshift-setup-{{ REDHAT_ANSIBLE_TOWER_VERSION }}.tar.gz"
    dest: "/tmp"
- name: Download OpenShift oc binary
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ REDHAT_OPENSHIFT_VERSION }}/openshift-client-linux-{{ REDHAT_OPENSHIFT_VERSION }}.tar.gz"
    dest: "/tmp/openshift-client-linux-{{ REDHAT_OPENSHIFT_VERSION }}.tar.gz"
- name: Unarchive OpenShift oc binary
  unarchive: 
    src: "/tmp/openshift-client-linux-{{ REDHAT_OPENSHIFT_VERSION }}.tar.gz"
    dest: "/tmp"
  args:
    creates: "/tmp/oc"
- name: Copy OpenShift oc binary
  copy: 
    remote_src: true
    src: "/tmp/oc"
    dest: "/usr/local/bin/oc"
    mode: "u=rwx,g=rx,o=rx"
  become: true
- name: Update Ansible Tower inventory
  template: 
    src: redhat_ansible_tower_inventory.j2
    dest: "/tmp/ansible-tower-openshift-setup-{{ REDHAT_ANSIBLE_TOWER_VERSION }}/inventory"
#- name: Run Ansible Tower setup script
#  shell: "./setup_openshift.sh"
#  args: 
#    chdir: "/tmp/ansible-tower-openshift-setup-{{ REDHAT_ANSIBLE_TOWER_VERSION }}"
